### ISSUE TITLE
Not Accurate

### ISSUE THREAD

**Issue by sunnykinger** [gabriel-TheCode/AndroidLocation#1]
Hi, I tried to run this on Emulator. The last known location is not updated when I change the location from emulator settings. 

Try these things:
1: Open app, it will give you the location which is currently set on emulator. 
2: Now let the map page stay, and change location to some other location on emulator. The location on the map will not jump to that new location which is understandable, but when I close the app from here and reopen it, still it shows old location.

If I add one line to your code, this situation is resolved, but it's not a perfect solution. 
`mMap.setMyLocationEnabled(true);`

Thank you

**Comment by gabriel-TheCode** [comment]
Thank you @sunnykinger, I corrected this in my last commit, it is probably not the optimal method but it works.
